### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by ocefpaf** [pyoceans/erddapy#10]
- [X] add the kwargs options to the `__init__` constructor;
- [X] validate the URL
- [X] add `.to_pandas()` and `.to_xarray()` methods
- [X] pass requests options along so we can use private server
